# Generated by Django 4.2.3 on 2023-07-29 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_shelter_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shelter',
            name='website',
        ),
    ]
