# Generated by Django 4.2.3 on 2023-07-29 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_shelter_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='shelter',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
